### ISSUE TITLE
The Subtotal is wrong. 

### ISSUE THREAD

**Issue by shaneliammurphy** [Boostly/order-client#12]
![image](https://user-images.githubusercontent.com/34665139/34134321-29b2b674-e417-11e7-8078-6f02fbb867eb.png)

It looks like it multiplied the Base value*100, then added the modifier*quantity correctly.

**Comment by mikeyamadeo** [comment]
The "servingPortions" price property was coming in as a string so we were doing string concatenation instead of math...
